[binance]
api_key = "GgujTrXy1HgUtdCf78V0I1UN36nGxrgoOMdWAJdg66lKZUqUubZejVBckeUnwnJF"
api_secret = "Sv5WKbPGIE7thqBznaTB7BzrwHYbEFfE3mvYo1EzNn6eTonHzYK6pDwl46eN9Z14"

[telegram]
token = "8144073534:AAHH8R79sAfoV6qjeHxuCAt1pYHq4Ezg9EY"
chat_id = "1012868061"

[app]
password = "619619"


# MySQL yapılandırması
[mysql]
host = "localhost"
port = 3306
database = "kripto_backtest"
user = "root"
password = "619619"