[binance]
api_key = "GgujTrXy1HgUtdCf78V0I1UN36nGxrgoOMdWAJdg66lKZUqUubZejVBckeUnwnJF"
api_secret = "Sv5WKbPGIE7thqBznaTB7BzrwHYbEFfE3mvYo1EzNn6eTonHzYK6pDwl46eN9Z14"

[telegram]
token = "8144073534:AAHH8R79sAfoV6qjeHxuCAt1pYHq4Ezg9EY"
chat_id = "1012868061"

[app]
password = "619619"


# PostgreSQL (eski - artık kullanılmıyor)
# [postgres]
# host = "localhost"
# port = "5432"
# database = "veritas_point_db"
# user = "veritas_user"
# password = "619619"

# Firebase Firestore yapılandırması
[firebase]
credentials_path = "C:/Users/Serce/Documents/GitHub/kripto-backtest-app/Desktop/kripto-backtest-app/kripto-backtest-app-firebase-adminsdk-fbsvc-bd82be3d82.json"
project_id = "kripto-backtest-app"


# Storage bucket (OPSİYONEL - boş bırakılırsa RL modelleri yerel dosya sistemine kaydedilir)
# storage_bucket = "your-firebase-project-id.appspot.com"